### ISSUE TITLE
directory name and module name don't match

### ISSUE THREAD

**Issue by threepistons** [NexusIS/puppet-mediawiki#6]
https://docs.puppet.com/puppet/latest/reference/modules_fundamentals.html#example explains that the module name, folder name, and manifests/init.pp class name must all be identical.  When I download the module from Puppet Forge, the directory name I get is **nexusis_mediawiki** instead of **mediawiki**.  This stops the module from working, but renaming the directory to **mediawiki** stops **puppet module** from managing the module.  A workaround is to symlink the directory name to the class name as follows:

```
cd /etc/puppetlabs/code/environments/production/modules
ln -s nexusis_mediawiki/ mediawiki
```

however, the proper solution is to change the directory name in this repo.

**Comment by aimonb** [comment]
Agreed! We will change the name.

**Comment by aimonb** [comment]
Hi, you can choose any name you want when checking out he module. There is no need for us to change our repo name. ex: git clone <url> mediawiki
