### ISSUE TITLE
MySQL passwords containing spaces don't work

### ISSUE THREAD

**Issue by threepistons** [NexusIS/puppet-mediawiki#7]
In my site.pp, I put

> db_root_password => 'my awesome diceware password',

I got

> Notice: /Stage[main]/Main/Node[hg-mediawiki.ncl.ac.uk]/Mediawiki::Instance[my_wiki1]/Exec[my_wiki1-install_script]/returns: Check the host, username and password and try again.
> Error: /usr/bin/php install.php my_wiki1 admin                            --pass puppet                                                     --email me@example.com                                           --server http://test-mediawiki                                   --scriptpath /my_wiki1                                             --dbtype mysql                                                    --dbserver localhost                                              --installdbuser root                                              --installdbpass my awesome diceware password                               --dbname wiki1                                               --dbuser wiki1_user                                               --dbpass super_long_password                                           --db-prefix wk                                          --confpath /etc/mediawiki/my_wiki1                          --lang en returned 1 instead of one of [0]
> Error: /Stage[main]/Main/Node[hg-mediawiki.ncl.ac.uk]/Mediawiki::Instance[my_wiki1]/Exec[my_wiki1-install_script]/returns: change from notrun to 0 failed: /usr/bin/php install.php my_wiki1 admin                            --pass puppet                                                     --email me@example.com                                            --server http://test-mediawiki                                    --scriptpath /my_wiki1                                             --dbtype mysql                                                    --dbserver localhost                                              --installdbuser root                                              --installdbpass my awesome diceware password                               --dbname wiki1                                               --dbuser wiki1_user                                               --dbpass super_long_password                                           --db-prefix wk                                          --confpath /etc/mediawiki/my_wiki1                          --lang en returned 1 instead of one of [0];

When I replaced with

> > db_root_password => 'my.awesome.diceware.password',

the wiki installed as expected.

**Comment by aimonb** [comment]
Thanks for finding this bug. Will will have a new version up shortly.

**Comment by aimonb** [comment]
Hi, what version of the mysql module are you using? The module passes the password directly to the mysql module. So if the bug still exists in the latest mysql module you should file a bug report for that module.
